### ISSUE TITLE
Regex fails on NXM links for XRebirth files

### ISSUE THREAD

**Issue by skwerlman** [TanninOne/modorganizer-uibase#13]
For whatever reason, files on the XRebirth nexus site have links of the structure `nxm:///modid/file/fileid`, not `nxm://game/modid/file/fileid`, so the current regex fails when it can't match a game.

A quick fix would be to change the regex to `nxm://([a-z0-9]+|)/mods/(\\d+)/files/(\\d+)` and check later whether `exp.cap(1)` is empty. I'd do this in a PR, but I have no idea how to compile CPP on Windows to test it (I usually develop on Linux).

**Comment by TanninOne** [comment]
This is a bug on nexusmods and should be fixed by now. Besides: MO doesn't even support XRebirth... ;)
